name: lint

on: [push, pull_request]

env:
  TFLINT_VERSION: v0.42.2
  TF_DIR: infra/

jobs:
  terraform:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.7
    - name: Run terraform fmt -check
      run: terraform fmt -check -recursive
    - name: Run terraform validate
      run: terraform -chdir=${{ env.TF_DIR }} init -backend=false && terraform -chdir=${{ env.TF_DIR }} validate # TODO is init required?

  tflint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: terraform-linters/setup-tflint@v2
      name: Setup TFLint
      with:
        tflint_version: ${{ env.TFLINT_VERSION }}
    - name: Init TFLint
      run: tflint --init
    - name: Run TFLint
      run: tflint -f compact ${{ env.TF_DIR }}

  tfsec:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Run tfsec
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        working_directory: ${{ env.TF_DIR }}
